### ISSUE TITLE
Small typo in UGX currency

### ISSUE THREAD

**Issue by tritas** [kalaspuff/stockholm#20]
Hi, just caught a small typo, where `decimal_digit` should be `decimal_digits`.

https://github.com/kalaspuff/stockholm/blob/bac2c520921a1682bbc940862c3e967456dac236/stockholm/currency.py#L812

I hope you don't mind if I don't submit a PR? Cheers,

**Comment by kalaspuff** [comment]
Hi! 👋  Thank you so much for reporting this, and sorry about the insanely long response time. 
I've been spending more time on other projects currently, and haven't had the time and energy to update my own packages.

Going through updates across the board now, and of course also got this fix in. It's pushed in version `0.4.1`.

It's always okay to put up PR:s if you run into something else! 🙏
